/* RoboticsLab, Copyright 2008-2010 SimLab Co., Ltd. All rights reserved.
 *
 * This library is commercial and cannot be redistributed, and/or modified
 * WITHOUT ANY ALLOWANCE OR PERMISSION OF SimLab Co., LTD.
 */
#ifndef __CONTROL_ALLEGRODOGCMD_H__
#define __CONTROL_ALLEGRODOGCMD_H__

#include "rCommand/rCmdManipulator.h"

#define ALLEGRODOGCMD_BASE			(RCMD_USER + 0x0100)

#define CMD_MOTION_READY			(ALLEGRODOGCMD_BASE + 2)
#define CMD_MOTION_RUN				(ALLEGRODOGCMD_BASE + 3)
#define CMD_MOTION_STOP				(ALLEGRODOGCMD_BASE + 4)
#define CMD_MOTION_TURNL			(ALLEGRODOGCMD_BASE + 5)
#define CMD_MOTION_TURNR			(ALLEGRODOGCMD_BASE + 6)
#define CMD_MOTION_HOP				(ALLEGRODOGCMD_BASE + 7)
#define CMD_MOTION_DN				(ALLEGRODOGCMD_BASE + 9)
#define CMD_MOTION_UP				(ALLEGRODOGCMD_BASE + 10)
#define CMD_MOTION_BACK				(ALLEGRODOGCMD_BASE + 11)

#define CMD_SPEED_UP				(ALLEGRODOGCMD_BASE + 101)
#define CMD_SPEED_DN				(ALLEGRODOGCMD_BASE + 102)

#define CMD_TEST_MODE_WALK			(ALLEGRODOGCMD_BASE + 201)
#define CMD_TEST_MODE_CONST_TORQUE	(ALLEGRODOGCMD_BASE + 202)
#define CMD_TEST_MODE_POSITION_SIN	(ALLEGRODOGCMD_BASE + 203)
#define CMD_TEST_MODE_TORQUE_SIN	(ALLEGRODOGCMD_BASE + 204)
#define CMD_TEST_MODE_DISABLE		(ALLEGRODOGCMD_BASE + 209)

#define PLOT_AHRS					0x0100

#endif
