#ifndef __RDEVICEALLEGRODOGMOTORCMD_H__
#define __RDEVICEALLEGRODOGMOTORCMD_H__

#define ALLEGRODOGMOTOR_CMD_BASE				(0x0000)

#define ALLEGRODOGMOTOR_CMD_OPMODE_POS			(0x01 + ALLEGRODOGMOTOR_CMD_BASE)
#define ALLEGRODOGMOTOR_CMD_OPMODE_VEL			(0x02 + ALLEGRODOGMOTOR_CMD_BASE)
#define ALLEGRODOGMOTOR_CMD_OPMODE_CUR			(0x03 + ALLEGRODOGMOTOR_CMD_BASE)

#define ALLEGRODOGMOTOR_CMD_HOME				(0x10 + ALLEGRODOGMOTOR_CMD_BASE)
#define ALLEGRODOGMOTOR_CMD_QUERY_STATUS		(0x11 + ALLEGRODOGMOTOR_CMD_BASE)

typedef struct tagMotorCommand_AllegroDog
{
	float q_des;
	float qdot_des;
	float tau_des;
} AllegroDog_MotorCommand_t;

#define ALLEGRODOGMOTOR_MONITOR_CURRENT			(0)
#define ALLEGRODOGMOTOR_MONITOR_OPMODE_DISPLAY	(1)
#define ALLEGRODOGMOTOR_MONITOR_OP_STATUS		(2)
#define ALLEGRODOGMOTOR_MONITOR_FALUT_STATUS	(3)

#endif // __RDEVICEALLEGRODOGMOTORCMD_H__
