#include "rCommand/rCmdDefine.h"

#ifndef __ALLEGRODOGCMD_H__
#define __ALLEGRODOGCMD_H__

#include "rCommand/rCmdManipulator.h"

#define ALLEGRODOG_CMD_BASE			(RCMD_USER + 0x0100)

#define CMD_MOTION_READY			(ALLEGRODOG_CMD_BASE + 2)
#define CMD_MOTION_RUN				(ALLEGRODOG_CMD_BASE + 3)
#define CMD_MOTION_STOP				(ALLEGRODOG_CMD_BASE + 4)
#define CMD_MOTION_TURNL			(ALLEGRODOG_CMD_BASE + 5)
#define CMD_MOTION_TURNR			(ALLEGRODOG_CMD_BASE + 6)

#define CMD_SPEED_UP				(ALLEGRODOG_CMD_BASE + 101)
#define CMD_SPEED_DN				(ALLEGRODOG_CMD_BASE + 102)

#define CMD_TEST_MODE_WALK			(ALLEGRODOG_CMD_BASE + 201)
#define CMD_TEST_MODE_CONST_TORQUE	(ALLEGRODOG_CMD_BASE + 202)
#define CMD_TEST_MODE_POSITION_SIN	(ALLEGRODOG_CMD_BASE + 203)
#define CMD_TEST_MODE_TORQUE_SIN	(ALLEGRODOG_CMD_BASE + 204)
#define CMD_TEST_MODE_DISABLE		(ALLEGRODOG_CMD_BASE + 209)

#define PLOT_AHRS					0x0100

#endif // __ALLEGRODOGCMD_H__
