#include "rCommand/rCmdDefine.h"

#ifndef __RDEVICEALLEGRODOGCANCMD_H__
#define __RDEVICEALLEGRODOGCANCMD_H__

#define CAN_CMD_BASE						(0x0000)

#define CAN_CMD_ENABLE						(0x01 + CAN_CMD_BASE)
#define CAN_CMD_DISABLE						(0x02 + CAN_CMD_BASE)
#define CAN_CMD_INIT_SYS					(0x03 + CAN_CMD_BASE)
#define CAN_CMD_RESET_ENC					(0x04 + CAN_CMD_BASE)
#define CAN_CMD_MOTOR_ON					(0x05 + CAN_CMD_BASE)
#define CAN_CMD_MOTOR_OFF					(0x06 + CAN_CMD_BASE)
#define CAN_CMD_STOP_SYS					(0x07 + CAN_CMD_BASE)
#define CAN_CMD_OPMODE_POSITION				(0x08 + CAN_CMD_BASE)
#define CAN_CMD_OPMODE_VELOCITY				(0x09 + CAN_CMD_BASE)
#define CAN_CMD_OPMODE_CURRENT				(0x0A + CAN_CMD_BASE)
#define CAN_CMD_SET_POS_TARGET_RELATIVE		(0x0B + CAN_CMD_BASE)
#define CAN_CMD_SET_POS_TARGET_ABSOLUTE		(0x0C + CAN_CMD_BASE)
#define CAN_CMD_SET_POS_MAX_VELOCITY		(0x0D + CAN_CMD_BASE)
#define CAN_CMD_HOMING						(0x0E + CAN_CMD_BASE)
#define CAN_CMD_QUERY_STATUS				(0x0F + CAN_CMD_BASE)

#define CAN_CMD_UPDATE_READ					(0x11 + CAN_CMD_BASE)
#define CAN_CMD_UPDATE_WRITE				(0x12 + CAN_CMD_BASE)

#endif // __RDEVICEALLEGRODOGCANCMD_H__
